### PR TITLE
Bugfix/issue12 First account creation sends email confirmation but is not needed

### PR DESCRIPTION
**Pull request by sdelrio**
Fix for Issue https://github.com/Bigjoos/U-232-V5/issues/12

Will not send email for first account (number of users == 0 when creating account).

### CODE REVIEW

**Comment by Bigjoos** [comment]
This change is not required. I've tested this extensively and found no issues at all after I changed the logic.

**Comment by sdelrio** [comment]
Ok, since PR was so many days ago, I will make a clean install with last code without this patch and test it again. Will make screenshots if it fails.

**Comment by sdelrio** [comment]
Steps followed:
1. Fresh intall (I used a VM: https://github.com/sdelrio/vagrant-u232-dev )
2. Versions used:
   PHP 7.0.11-1~dotdeb+8.1
   php7.0-fpm 7.0.11-1~dotdeb+8.1
   Apache/2.4.10 (Debian)
   Debian Version 8.1
3. Before creating user, users is empty:

```
mysql> select * from users;
Empty set (0.00 sec)
```
1. Create user:

image

image
1. Check user created correctly:

```
mysql> select id,username,email from users;
+----+----------+-------------------------+
| id | username | email                   |
+----+----------+-------------------------+
|  1 | admin    | admin@u232v5.vagrant.vm |
+----+----------+-------------------------+
1 row in set (0.00 sec)
```
1. Email received (but not needed since first accound is already confirmed).

```
Message-ID: rZvF4DAZFe83kcs3h-KeFV7FUEq8wZ9WMtl2xquaD74=@mailhog.example
Received: from localhost by mailhog.example (Go-MailHog)
          id rZvF4DAZFe83kcs3h-KeFV7FUEq8wZ9WMtl2xquaD74=@mailhog.example; Sat, 15 Oct 2016 17:11:17 +0200
Return-Path: <nobody@u232v5>
Subject:  user registration confirmation
To: admin@u232v5.vagrant.vm
X-PHP-Originating-Script: 33:takesignup.php


You have requested a new user account on  and you have
specified this address (admin@u232v5.vagrant.vm) as user contact.

If you did not do this, please ignore this email. The person who entered your
email address had the IP address 192.168.44.2. Please do not reply.

To confirm your user registration, you have to follow this link:

http://localhost:8080/confirm.php?id=1&secret=

After you do this, you will be able to use your new account. If you fail to
do this, your account will be deleted within a few days. We urge you to read
the RULES and FAQ before you start using .
```

**Comment by Bigjoos** [comment]
No need for this change.

**Pull request closed without merging**
